on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Nodejs
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: setup AWS env
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
      run: |
        npm i 
        npm install -g @angular/cli@8.0.6
        ng build --prod --vendor-chunk --common-chunk --delete-output-path --buildOptimizer
        mkdir ~/.aws
        echo -e "[default]\naws_access_key_id = ${{ secrets.dev_access_key }}\naws_secret_access_key = ${{ secrets.dev_secret_key }}" > ~/.aws/credentials
        chmod 600 ~/.aws/credentials
        echo -e "[default]\nregion=us-east-1" > ~/.aws/config
        sudo apt-get install python-pip
        sudo pip install awscli
        aws s3 cp dist/ s3://dev-houmme-main-site
