on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: setup AWS env
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
      run: |
        node -i
        ng build --prod --vendor-chunk --common-chunk --delete-output-path --buildOptimizer
        mkdir ~/.aws
        echo -e "[default]\naws_access_key_id = ${{ secrets.AWS_KEY }}\naws_secret_access_key = ${{ secrets.AWS_SECRET }}" > ~/.aws/credentials
        chmod 600 ~/.aws/credentials
        echo -e "[default]\nregion=us-east-1" > ~/.aws/config
